import {
  LEVEL_THEMES,
  PLACEMENT_PLAYER,
  PLACEMENT_GIFT,
  PLACEMENT_WOOD,
  PLACEMENT_NPC,
  NPCS,
  BEHAVIOURS,
  PLACEMENT_SOLID,
  GIFTS,
  PLACEMENT_TILE,
  PLACEMENT_GOAL_NPC,
  PLACEMENT_HEART,
  PLACEMENT_END,
} from "../helpers/consts";
import { TILES } from "../helpers/tiles";

const placements = [
  { x: 4, y: 9, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_LEFT },
  { x: 5, y: 9, type: PLACEMENT_TILE, tile: TILES.CARPET_CENTER },
  { x: 6, y: 9, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_RIGHT },
  { x: 4, y: 8, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_LEFT },
  { x: 5, y: 8, type: PLACEMENT_TILE, tile: TILES.CARPET_CENTER },
  { x: 6, y: 8, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_RIGHT },
  { x: 4, y: 7, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_LEFT },
  { x: 5, y: 7, type: PLACEMENT_TILE, tile: TILES.CARPET_CENTER },
  { x: 6, y: 7, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_RIGHT },
  { x: 4, y: 6, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_LEFT },
  { x: 5, y: 6, type: PLACEMENT_TILE, tile: TILES.CARPET_CENTER },
  { x: 6, y: 6, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_RIGHT },
  { x: 4, y: 5, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_LEFT },
  { x: 5, y: 5, type: PLACEMENT_TILE, tile: TILES.CARPET_CENTER },
  { x: 6, y: 5, type: PLACEMENT_TILE, tile: TILES.CARPET_EDGE_RIGHT },
  { x: 4, y: 4, type: PLACEMENT_TILE, tile: TILES.CARPET_TOP_LEFT },
  { x: 5, y: 4, type: PLACEMENT_TILE, tile: TILES.CARPET_TOP_CENTER },
  { x: 6, y: 4, type: PLACEMENT_TILE, tile: TILES.CARPET_TOP_RIGHT },
  { x: 1, y: 1, type: PLACEMENT_SOLID, tile: TILES.FLOWER_POT },
  { x: 9, y: 1, type: PLACEMENT_SOLID, tile: TILES.FLOWER_POT },
  { x: 5, y: 9, type: PLACEMENT_PLAYER },
  {
    x: 2,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 2,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 8,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 9,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 8,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 9,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 8,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 9,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.GOBLIN,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 2,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 2,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 2,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 2,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC1,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 8,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 6,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },
  {
    x: 1,
    y: 4,
    type: PLACEMENT_NPC,
    npc: NPCS.NPC2,
    behaviour: BEHAVIOURS.STATIC,
  },

  {
    x: 2,
    y: 1,
    type: PLACEMENT_NPC,
    npc: NPCS.CAT,
    behaviour: BEHAVIOURS.RANDOM,
    small: true,
  },

  {
    x: 4,
    y: 3,
    type: PLACEMENT_GOAL_NPC,
    behaviour: BEHAVIOURS.STATIC,
  },
  { x: 5, y: 3, type: PLACEMENT_HEART },
  { x: 6, y: 3, type: PLACEMENT_END },
];
const game = {
  theme: LEVEL_THEMES.ENDING,
  tilesWidth: 9,
  tilesHeight: 9,
  placements: placements,
};

export default game;
